# 选择开发环境的配置文件
spring:
  profiles:
    active: dev
lesson: SpringBootDemo
enterprise:
  name: leohan
  age: 16
  tel: 4001685000
  subjects:
    - java
    - python
    - c++
---
# 开发环境的配置文件
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
---
# 正式环境的配置文件
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8081
---
# 测试环境的配置文件
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8082
